image: ubuntu:bionic

cache:
  paths:
    - .cache/

stages:
  - test:app
  - make:packages
  - test:packages
  - export:packages
  - merge:packages
  - tag:packages
  - tag:app

variables:
  GIT_REPO_APP_URL: "git@gitlab.com:dex4er/ts-node-github-api-example.git"
  GIT_REPO_PACKAGES_URL: "git@gitlab.com:dex4er/ts-node-github-api-example-packages.git"
  NODE_VERSION: "10"

test:app:node-10:
  stage: test:app
  before_script:
    - . .gitlab-ci/before/environ.sh
    - . .gitlab-ci/before/apt.sh
    - . .gitlab-ci/before/gpg.sh
    - . .gitlab-ci/before/node.sh
    - . .gitlab-ci/before/yarn.sh
  script:
    - . .gitlab-ci/test-app.sh
  except:
    - tags
  variables:
    TEST_AUDIT: "yes"

test:app:node-12:
  stage: test:app
  before_script:
    - . .gitlab-ci/before/environ.sh
    - . .gitlab-ci/before/apt.sh
    - . .gitlab-ci/before/gpg.sh
    - . .gitlab-ci/before/node.sh
    - . .gitlab-ci/before/yarn.sh
  script:
    - . .gitlab-ci/test-app.sh
  except:
    - tags
  variables:
    NODE_VERSION: "12"

make:packages:
  stage: make:packages
  before_script:
    - . .gitlab-ci/before/environ.sh
    - . .gitlab-ci/before/apt.sh
    - . .gitlab-ci/before/gpg.sh
    - . .gitlab-ci/before/node.sh
    - . .gitlab-ci/before/yarn.sh
  script:
    - . .gitlab-ci/make-packages.sh
  only:
    - develop
  artifacts:
    paths:
      - .packages/
    expire_in: 1 week

test:packages:node-10:
  stage: test:packages
  before_script:
    - . .gitlab-ci/before/environ.sh
    - . .gitlab-ci/before/apt.sh
    - . .gitlab-ci/before/gpg.sh
    - . .gitlab-ci/before/node.sh
    - . .gitlab-ci/before/yarn.sh
  script:
    - . .gitlab-ci/test-packages.sh
  only:
    - develop

test:packages:node-12:
  stage: test:packages
  before_script:
    - . .gitlab-ci/before/environ.sh
    - . .gitlab-ci/before/apt.sh
    - . .gitlab-ci/before/gpg.sh
    - . .gitlab-ci/before/node.sh
    - . .gitlab-ci/before/yarn.sh
  script:
    - . .gitlab-ci/test-packages.sh
  only:
    - develop
  variables:
    NODE_VERSION: "12"

export:packages:
  stage: export:packages
  before_script:
    - . .gitlab-ci/before/environ.sh
    - . .gitlab-ci/before/apt.sh
    - . .gitlab-ci/before/git.sh
    - . .gitlab-ci/before/ssh-private-key.sh
  script:
    - . .gitlab-ci/export.sh
  only:
    - develop
  variables:
    ARTIFACTS_PATH: ".packages/"
    GIT_REPO_URL: "$GIT_REPO_PACKAGES_URL"

merge:packages:
  stage: merge:packages
  before_script:
    - . .gitlab-ci/before/environ.sh
    - . .gitlab-ci/before/apt.sh
    - . .gitlab-ci/before/git.sh
    - . .gitlab-ci/before/ssh-private-key.sh
  script:
    - . .gitlab-ci/merge.sh
  only:
    - master
  variables:
    GIT_MERGE_FROM: "develop"
    GIT_REPO_URL: "$GIT_REPO_PACKAGES_URL"

tag:packages:
  stage: tag:packages
  before_script:
    - . .gitlab-ci/before/environ.sh
    - . .gitlab-ci/before/apt.sh
    - . .gitlab-ci/before/jq.sh
    - . .gitlab-ci/before/git.sh
    - . .gitlab-ci/before/ssh-private-key.sh
  script:
    - . .gitlab-ci/tag.sh
  only:
    - master
  variables:
    GIT_REPO_URL: "$GIT_REPO_PACKAGES_URL"

tag:app:
  stage: tag:app
  before_script:
    - . .gitlab-ci/before/environ.sh
    - . .gitlab-ci/before/apt.sh
    - . .gitlab-ci/before/jq.sh
    - . .gitlab-ci/before/git.sh
    - . .gitlab-ci/before/ssh-private-key.sh
  script:
    - . .gitlab-ci/tag.sh
  only:
    - master
  variables:
    GIT_REPO_URL: "$GIT_REPO_APP_URL"
