sudo: false

language: node_js

matrix:
  include:
    - node_js: "node"
      env: NPM_AUDIT=yes NPM_RUN_LINT=yes
    - node_js: "10"

before_install:
  - npm install -g yarn

install:
  - set -e
  - yarn
  - if [ -n "$NPM_AUDIT" ]; then yarn audit; fi

script:
  - npm pack
  - if [ -n "$NPM_RUN_LINT" ]; then yarn lint; fi
  - yarn test:script
  - git diff --stat --exit-code
  - for f in $(git ls-files --others --exclude-standard); do git diff --no-index --stat --exit-code /dev/null $next; done
  - yarn clean
