sudo: false

language: node_js

matrix:
  include:
    - node_js: "node"
      env: NPM_AUDIT=yes NPM_PACK=yes NPM_RUN_LINT=yes
    - node_js: "10"
    - node_js: "8"

install:
  - set -e
  - npm install
  - if [ -n "$NPM_AUDIT" ]; then npm audit; fi

script:
  - npm run github-apiv4-get-schema
  - if [ -n "$NPM_PACK" ]; then npm pack; else npm run prepack; fi
  - if [ -n "$NPM_RUN_LINT" ]; then npm run lint; fi
  - npm run github-apiv4-viewer-query
  - git diff --stat --exit-code
  - for f in $(git ls-files --others --exclude-standard); do git diff --no-index --stat --exit-code /dev/null $next; done
  - npm run clean
